steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/bible-search:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/bible-search:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - 'bible-search'
      - '--image=gcr.io/$PROJECT_ID/bible-search:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=600'
      - '--cpu-boost'
      - '--startup-cpu-boost'
      - '--min-instances=0'
      - '--max-instances=3'

images:
  - 'gcr.io/$PROJECT_ID/bible-search:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
