apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: bible-search
spec:
  template:
    metadata:
      annotations:
        # Use gen2 execution environment for better performance
        run.googleapis.com/execution-environment: gen2
        # CPU is always allocated (not just during request processing)
        run.googleapis.com/cpu-throttling: "false"
        # Boost CPU during startup
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 8Gi
              cpu: "4"
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
            # SQLite embedding store (pre-built and included in Docker image)
            - name: EMBEDDING_SQLITE_ENABLED
              value: "true"
            - name: EMBEDDING_SQLITE_PATH
              value: "classpath:embeddings/bible-embeddings.db"
          # Startup probe - waits for app to be ready (up to 15 minutes for first-time embedding generation)
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 30
          # Liveness probe - checks if app is still alive
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true
